export default {
  category: [
    {
      id: '1',
      categoryname: 'Electrical Service',
      icon: require('../assets/images/icon1.png'),
    },
    {
      id: '2',
      categoryname: 'Repairing',
      icon: require('../assets/images/icon2.png'),
    },
    {
      id: '3',
      categoryname: 'Cleaning',
      icon: require('../assets/images/icon3.png'),
    },
    {
      id: '4',
      categoryname: 'Plumbing',
      icon: require('../assets/images/icon4.png'),
    },
    {
      id: '5',
      categoryname: 'Laundry',
      icon: require('../assets/images/icon5.png'),
    },
    {
      id: '6',
      categoryname: 'Dishes',
      icon: require('../assets/images/icon6.png'),
    },
    {
      id: '7',
      categoryname: 'Car Wash',
      icon: require('../assets/images/icon7.png'),
    },
    {
      id: '8',
      categoryname: 'Carpentry',
      icon: require('../assets/images/icon8.png'),
    },
    {
      id: '9',
      categoryname: 'Dusting',
      icon: require('../assets/images/icon9.png'),
    },
    {
      id: '10',
      categoryname: 'Construction',
      icon: require('../assets/images/icon10.png'),
    },
  ],
  subcategory: [
    {
      id: '1',
      categoryid: '1',
      subcategoryname: 'Electrical Service',
      image: require('../assets/images/electric.png'),
      rating: '4.9',
      dis: 'Want the best electric service? we are here for you.',
      bgcolor: '#D6A59A',
    },
    {
      id: '2',
      categoryid: '2',
      subcategoryname: 'Repairing',
      image: require('../assets/images/repairing.png'),
      rating: '4.8',
      dis:
        'Looking for a good service for repairing your appliances? You are at the right place.',
      bgcolor: '#FFB774',
    },
    {
      id: '3',
      categoryid: '3',
      subcategoryname: 'Cleaning',
      image: require('../assets/images/cleaning.png'),
      rating: '4.9',
      dis: 'We offer the best home cleaning services in the town.',
      bgcolor: '#E3B7E6',
    },
    {
      id: '4',
      categoryid: '4',
      subcategoryname: 'Plumbing',
      image: require('../assets/images/plumbing.png'),
      rating: '4.7',
      dis: 'Number of best plumbers availbable on our services.',
      bgcolor: '#B37C7C',
    },
    {
      id: '5',
      categoryid: '5',
      subcategoryname: 'Laundry',
      image: require('../assets/images/laundry.png'),
      rating: '4.4',
      dis: 'Best dish washing services available.',
      bgcolor: '#8E8686',
    },
    {
      id: '6',
      categoryid: '6',
      subcategoryname: 'Dishes',
      image: require('../assets/images/Dish.png'),
      rating: '4.7',
      dis: 'Best dish washing services available.',
      bgcolor: '#FF90C8',
    },
    {
      id: '7',
      categoryid: '7',
      subcategoryname: 'Car Wash',
      image: require('../assets/images/CarWash.png'),
      rating: '4.4',
      dis: 'We offer the best car wash services in the town.',
      bgcolor: '#D07373',
    },
    {
      id: '8',
      categoryid: '8',
      subcategoryname: 'Carpentry',
      image: require('../assets/images/carpentry.png'),
      rating: '4.9',
      dis: 'Want the best carpenters? we are here for you.',
      bgcolor: '#957E66',
    },
    {
      id: '9',
      categoryid: '9',
      subcategoryname: 'Dusting',
      image: require('../assets/images/dusting.png'),
      rating: '4.7',
      dis: 'Best dusting services available.',
      bgcolor: '#B2D09D',
    },
    {
      id: '10',
      categoryid: '10',
      subcategoryname: 'Construction',
      image: require('../assets/images/construction2.png'),
      rating: '4.8',
      dis: 'We offer the best home construction services in the town.',
      bgcolor: '#617E8A',
    },
  ],
  banner: [
    {
      bannerid: '1',
      categoryid: '3',
      bannerimage: require('../assets/images/icon3.png'),
      bannerdis: 'We offer the best home cleaning services in the town.',
    },
    {
      bannerid: '2',
      categoryid: '4',
      bannerimage: require('../assets/images/icon4.png'),
      bannerdis: 'Number of best plumbers availbable on our services.',
    },
    {
      bannerid: '3',
      categoryid: '6',
      bannerimage: require('../assets/images/icon6.png'),
      bannerdis: 'Best dish washing services available.',
    },
    {
      bannerid: '4',
      categoryid: '8',
      bannerimage: require('../assets/images/icon8.png'),
      bannerdis: 'Want the best carpenters? we are here for you.',
    },
  ],
};
